### ISSUE TITLE
fix CI failures

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/networks#366]
```[tasklist]
### Tasks
- [x] empty file in gentx dir causes failure (either by removing file or making the tool ignore `.files`) (see #367)
- [x] looks like bot not allowed to keep track of PRs when they come from forks (see https://github.com/celestiaorg/networks/actions/runs/6597567930/job/17924687535?pr=364; but weirdly https://github.com/celestiaorg/networks/actions/runs/6597322356/job/17924245542?pr=362 does not expose the same behavior)
- [x] bot can't comment (maybe also related to forks?): also see: https://github.com/celestiaorg/networks/actions/runs/6597322356/job/17924245542?pr=362
- [x] amount check should be utia instead of tia (e.g. expected between 1 and 9, got 8000000)
```
